In [1]:
import tensorflow as tf

/Users/Kerryn/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [2]:
from tensorflow.examples.tutorials.mnist import  input_data

In [3]:
mnist = input_data.read_data_sets('MNIST_data/',one_hot=True)

Instructions for updating:
Please use alternatives such as official/mnist/dataset.py from tensorflow/models.
Instructions for updating:
Please write your own downloading logic.
Instructions for updating:
Please use urllib or similar directly.
Successfully downloaded train-images-idx3-ubyte.gz 9912422 bytes.
Instructions for updating:
Please use tf.data to implement this functionality.
Extracting MNIST_data/train-images-idx3-ubyte.gz
Successfully downloaded train-labels-idx1-ubyte.gz 28881 bytes.
Instructions for updating:
Please use tf.data to implement this functionality.
Extracting MNIST_data/train-labels-idx1-ubyte.gz
Instructions for updating:
Please use tf.one_hot on tensors.
Successfully downloaded t10k-images-idx3-ubyte.gz 1648877 bytes.
Extracting MNIST_data/t10k-images-idx3-ubyte.gz
Successfully downloaded t10k-labels-idx1-ubyte.gz 4542 bytes.
Extracting MNIST_data/t10k-labels-idx1-ubyte.gz
Instructions for updating:
Please use alternatives such as official/mnist/dataset.py fr

In [4]:
type(mnist)

tensorflow.contrib.learn.python.learn.datasets.base.Datasets

In [6]:
mnist.train.images.shape

(55000, 784)

In [7]:
mnist.train.num_examples

55000

In [8]:
mnist.test.num_examples

10000

In [29]:
import matplotlib.pyplot as plt
%matplotlib

Using matplotlib backend: MacOSX


In [14]:
mnist.train.images[1].shape

(784,)

In [15]:
mnist.train.images[1].reshape(28,28)

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.    

In [19]:
plt.imshow(mnist.train.images[1].reshape(28,28))

plt.show()

In [21]:
print('hi, hello')

hi, hello


In [33]:
plt.imshow(mnist.train.images[1].reshape(28,28),cmap='gist_gray',aspect=0.02)

plt.show()

ERROR! Session/line number was not unique in database. History logging moved to new session 96


In [27]:
plt.imshow(mnist.train.images[3].reshape(28,28),cmap='gist_gray')

# Part 2

In [35]:
x= tf.placeholder(tf.float32,shape=[None,784])

In [36]:
x

<tf.Tensor 'Placeholder:0' shape=(?, 784) dtype=float32>

In [37]:
w = tf.Variable(tf.zeros([784,10]))

In [38]:
b = tf.Variable(tf.zeros([10]))

** x*w*b = y 
input * weight * bias = output**

In [40]:
y = tf.matmul(x,w) + b

In [41]:
y_true= tf.placeholder(tf.float32,shape=[None,10])

In [42]:
cross_entropy = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits_v2(labels= 
                                                                          y_true,
                                                                         logits=y))

# how we define the error

In [43]:
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.5)

# how we solve for the error

In [44]:
train= optimizer.minimize(cross_entropy)

In [45]:
init = tf.global_variables_initializer()

In [47]:
with tf.Session() as sess:
    sess.run(init)
    
    for step in range(1000):
        
        batch_x, batch_y = mnist.train.next_batch(100)
        
        sess.run(train,feed_dict={x:batch_x, y_true:batch_y})
        
    matches = tf.equal(tf.argmax(y,1),tf.argmax(y_true,1))
    
    acc = tf.reduce_mean(tf.cast(matches, tf.float32))
    
    print(sess.run(acc,feed_dict= {x:mnist.test.images, y_true:mnist.test.labels}))

0.9173


# Part 3 - Estimators

In [59]:
import pandas as pd

In [60]:
df= pd.read_csv('iris.csv')

In [61]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0     0.0  
1     0.0  
2     0.0  
3     0.0  
4     0.0

In [62]:
df.columns

Index(['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)',
       'petal width (cm)', 'target'],
      dtype='object')

In [63]:
df.columns= ['sepal_length','sepal_width','petal_length','petal_width','target']

In [64]:
df['target'] = df['target'].apply(int)

In [65]:
df.head()

sepal_length  sepal_width  petal_length  petal_width  target
0           5.1          3.5           1.4          0.2       0
1           4.9          3.0           1.4          0.2       0
2           4.7          3.2           1.3          0.2       0
3           4.6          3.1           1.5          0.2       0
4           5.0          3.6           1.4          0.2       0

In [66]:
y = df['target']

In [73]:
X= df.drop('target',axis=1)

In [74]:
from sklearn.model_selection import  train_test_split

In [75]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

In [76]:
import tensorflow as tf

** Create feature columns **

In [77]:
X.columns

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width'], dtype='object')

In [78]:
feat_cols = []

for col in X.columns:
    feat_cols.append(tf.feature_column.numeric_column(col))

In [79]:
feat_cols

[_NumericColumn(key='sepal_length', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None),
 _NumericColumn(key='sepal_width', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None),
 _NumericColumn(key='petal_length', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None),
 _NumericColumn(key='petal_width', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None)]

** Create an imput function **

In [81]:
input_fun = tf.estimator.inputs.pandas_input_fn(x= X_train, y=y_train, batch_size=10,
                                   num_epochs=5, shuffle=True)

In [82]:
classifier = tf.estimator.DNNClassifier(hidden_units=[10,20,10], 
                                       n_classes=3, feature_columns= feat_cols)

INFO:tensorflow:Using default config.
INFO:tensorflow:Using config: {'_model_dir': '/var/folders/jb/bgsbb9n16hv85gggk52j8z000000gp/T/tmpi8jky5p9', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': None, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_train_distribute': None, '_device_fn': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x1c256ca358>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}


In [85]:
classifier.train(input_fn=input_fun, steps=50)

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Saving checkpoints for 0 into /var/folders/jb/bgsbb9n16hv85gggk52j8z000000gp/T/tmpi8jky5p9/model.ckpt.
INFO:tensorflow:loss = 18.42762, step = 1
INFO:tensorflow:Saving checkpoints for 50 into /var/folders/jb/bgsbb9n16hv85gggk52j8z000000gp/T/tmpi8jky5p9/model.ckpt.
INFO:tensorflow:Loss for final step: 6.481702.


** Predictions **

In [86]:
pred_fn = tf.estimator.inputs.pandas_input_fn(x= X_test, batch_size=len(X_test),
                                             shuffle=False)

In [87]:
predictions = list(classifier.predict(input_fn=pred_fn))

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from /var/folders/jb/bgsbb9n16hv85gggk52j8z000000gp/T/tmpi8jky5p9/model.ckpt-50
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.


In [90]:
predictions

[{'class_ids': array([1]),
  'classes': array([b'1'], dtype=object),
  'logits': array([0.03919251, 0.13034546, 0.08861051], dtype=float32),
  'probabilities': array([0.31785426, 0.34818915, 0.33395657], dtype=float32)},
 {'class_ids': array([0]),
  'classes': array([b'0'], dtype=object),
  'logits': array([ 2.957837  ,  0.36989042, -0.45317495], dtype=float32),
  'probabilities': array([0.9023789 , 0.06783565, 0.02978552], dtype=float32)},
 {'class_ids': array([1]),
  'classes': array([b'1'], dtype=object),
  'logits': array([-0.04658327,  0.1233055 ,  0.104533  ], dtype=float32),
  'probabilities': array([0.29865858, 0.35396206, 0.3473793 ], dtype=float32)},
 {'class_ids': array([2]),
  'classes': array([b'2'], dtype=object),
  'logits': array([-0.24540561,  0.10496385,  0.14049767], dtype=float32),
  'probabilities': array([0.2570341 , 0.36488354, 0.37808236], dtype=float32)},
 {'class_ids': array([0]),
  'classes': array([b'0'], dtype=object),
  'logits': array([ 2.423352  ,  0.326

In [92]:
final_pred = []

for pred in predictions:
    final_pred.append(pred['class_ids'][0])

In [93]:
from sklearn.metrics import classification_report, confusion_matrix

In [96]:
print(classification_report(y_test,final_pred))

             precision    recall  f1-score   support

          0       0.94      1.00      0.97        17
          1       1.00      0.42      0.59        12
          2       0.73      1.00      0.84        16

avg / total       0.88      0.84      0.82        45



In [95]:
print(confusion_matrix(y_test,final_pred))

[[17  0  0]
 [ 1  5  6]
 [ 0  0 16]]
